services:
  - type: web
    name: ttech-site
    env: node
    plan: free
    autoDeploy: true
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: PORT
        value: 3000
      - key: GA_MEASUREMENT_ID
        value: ""
      - key: SMTP_HOST
        value: ""
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_SECURE
        value: "false"
      - key: SMTP_USER
        value: ""
      - key: SMTP_PASS
        value: ""
      - key: MAIL_TO
        value: "mnsimire@ttech.live"
      - key: MAIL_FROM
        value: "no-reply@ttech.live"